import Link from "next/link";
import { getHistory, getTickerChanges, getWatchlist, getPortfolio, getInvestigation, getTimeline } from "@/lib/api";
import type { Analysis, ChangeReport, WatchlistItem, Portfolio, EdgePosition, Investigation, Timeline } from "@/lib/types";
import TickerDetail from "./detail";

// ดึงสดทุกครั้ง (เหมือนหน้าแรก) — ไม่ cache
export const dynamic = "force-dynamic";

export default async function TickerPage({
  params,
}: {
  params: Promise<{ symbol: string }>;
}) {
  const { symbol } = await params;
  const ticker = symbol.toUpperCase();

  let history: Analysis[] = [];
  let change: ChangeReport | null = null;
  let watchItem: WatchlistItem | undefined;
  let edge: EdgePosition | undefined;
  let investigation: Investigation | null = null;
  let timeline: Timeline | null = null;
  let error: string | null = null;
  try {
    const [h, c, watchlist, portfolio, inv, tl]: [Analysis[], ChangeReport, WatchlistItem[], Portfolio, Investigation | null, Timeline | null] =
      await Promise.all([
        getHistory(ticker),
        getTickerChanges(ticker),
        getWatchlist(),
        getPortfolio(),
        getInvestigation(ticker),
        getTimeline(ticker),
      ]);
    history = h;
    change = c;
    watchItem = watchlist.find((w) => w.ticker === ticker);
    edge = portfolio.positions.find((p) => p.ticker === ticker);
    investigation = inv;
    timeline = tl;
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }

  return (
    <main className="wrap">
      <Link href="/" className="back">
        ← กลับหน้ารวม
      </Link>

      {error ? (
        <div className="error">Cannot reach the API ({error}).</div>
      ) : history.length === 0 ? (
        <div className="error">
          ยังไม่มีผลวิเคราะห์สำหรับ <strong>{ticker}</strong> — จะถูกวิเคราะห์ในรอบ agent ถัดไป
        </div>
      ) : (
        <TickerDetail
          ticker={ticker}
          history={history}
          changes={change?.changes ?? []}
          watchItem={watchItem}
          edge={edge}
          investigation={investigation}
          timeline={timeline}
        />
      )}

      <p className="disclaimer">
        Educational research tool. Summaries are generated by an LLM from public data and may be
        wrong — always verify against primary sources. Not investment advice.
      </p>
    </main>
  );
}
