import { getAnalyses } from "@/lib/api";
import type { Analysis } from "@/lib/types";

// server component: ดึงจาก FastAPI ตอน render (no-store = สดเสมอ)
export const dynamic = "force-dynamic";

function pct(x: number | null | undefined) {
  return x == null ? "—" : `${Math.round(x * 100)}%`;
}

function AnalysisCard({ a }: { a: Analysis }) {
  const s = a.summary;
  return (
    <div className="card">
      <div className="card-head">
        <span className="ticker">{a.ticker}</span>
        <span className="price">${a.price?.toFixed(2)}</span>
      </div>

      <div className="badges">
        <span className={`badge b-${s.fundamental_strength}`}>{s.fundamental_strength}</span>
        <span className={`badge b-${s.valuation_view}`}>{s.valuation_view}</span>
        <span className={`badge b-${s.sentiment}`}>{s.sentiment}</span>
      </div>

      {s.weak_points.length > 0 && (
        <>
          <div className="section-title">Weak points</div>
          <ul className="list weak">
            {s.weak_points.map((w, i) => (
              <li key={i}>
                <span className="area">{w.area}:</span> {w.detail}
              </li>
            ))}
          </ul>
        </>
      )}

      <div className="section-title">Thesis-relevant news</div>
      <ul className="list news">
        {s.thesis_relevant_news.length > 0 ? (
          s.thesis_relevant_news.map((n, i) => <li key={i}>{n}</li>)
        ) : (
          <li className="noise">All recent news is noise (no thesis impact)</li>
        )}
      </ul>

      <div className="meta">
        <span>conf {a.confidence}</span>
        <span className={a.price_ok ? "ok" : "bad"}>price {a.price_ok ? "✓" : "✗"}</span>
        <span>news {pct(a.news_grounded_ratio)}</span>
        <span>facts {pct(a.facts_grounded_ratio)}</span>
        <span style={{ marginLeft: "auto" }}>{a.run_at.replace("T", " ")}</span>
      </div>
    </div>
  );
}

export default async function Home() {
  let analyses: Analysis[] = [];
  let error: string | null = null;
  try {
    analyses = await getAnalyses();
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }

  return (
    <main className="wrap">
      <header className="top">
        <h1>Investment Research Agent</h1>
        <p>Latest fundamental analysis per watchlist ticker · research, not advice</p>
      </header>

      {error ? (
        <div className="error">
          Cannot reach the API ({error}). Start it with{" "}
          <code>uvicorn src.api.main:app --port 8000</code>
        </div>
      ) : analyses.length === 0 ? (
        <div className="error">
          No analyses yet. Run the agent: <code>python -c &quot;from src.agent.loop import run_watchlist; run_watchlist()&quot;</code>
        </div>
      ) : (
        <div className="grid">
          {analyses.map((a) => (
            <AnalysisCard key={a.id} a={a} />
          ))}
        </div>
      )}

      <p className="disclaimer">
        Educational research tool. Summaries are generated by an LLM from public data and may be
        wrong — always verify against primary sources. Not investment advice.
      </p>
    </main>
  );
}
