import Link from "next/link";
import { getAnalyses, getWatchlist, getChanges, getPortfolio, getHealthTrends } from "@/lib/api";
import type { Analysis, WatchlistItem, ChangeReport, Portfolio, HealthTrends } from "@/lib/types";
import Dashboard from "./dashboard";

// server component: ดึงจาก FastAPI ตอน render (no-store = สดเสมอ)
export const dynamic = "force-dynamic";

const EMPTY_PORTFOLIO: Portfolio = {
  benchmark: "VT",
  positions: [],
  beating_benchmark: 0,
  total_positions: 0,
  total_value: null,
  total_cost: null,
  total_pnl: null,
  total_return: null,
};

export default async function Home() {
  let analyses: Analysis[] = [];
  let watchlist: WatchlistItem[] = [];
  let changes: ChangeReport[] = [];
  let portfolio: Portfolio = EMPTY_PORTFOLIO;
  let healthTrends: HealthTrends = {};
  let error: string | null = null;
  try {
    [analyses, watchlist, changes, portfolio, healthTrends] = await Promise.all([
      getAnalyses(),
      getWatchlist(),
      getChanges(),
      getPortfolio(),
      getHealthTrends(),
    ]);
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }

  return (
    <main className="wrap">
      <header className="top">
        <div className="top-head">
          <h1>Investment Research Agent</h1>
          <div className="nav-links">
            <Link href="/chat" className="nav-link">ถามพอร์ต →</Link>
            <Link href="/macro" className="nav-link">เรดาร์มหภาค →</Link>
            <Link href="/screener" className="nav-link">Screener →</Link>
            <Link href="/portfolio" className="nav-link">Portfolio →</Link>
          </div>
        </div>
        <p>Latest fundamental analysis per watchlist ticker · research, not advice</p>
      </header>

      {error ? (
        <div className="error">
          Cannot reach the API ({error}). Start it with{" "}
          <code>uvicorn src.api.main:app --port 8000</code>
        </div>
      ) : (
        <Dashboard
          analyses={analyses}
          watchlist={watchlist}
          changes={changes}
          portfolio={portfolio}
          healthTrends={healthTrends}
        />
      )}

      <p className="disclaimer">
        Educational research tool. Summaries are generated by an LLM from public data and may be
        wrong — always verify against primary sources. Not investment advice.
      </p>
    </main>
  );
}
