import { getAnalyses, getWatchlist, getChanges } from "@/lib/api";
import type { Analysis, WatchlistItem, ChangeReport } from "@/lib/types";
import Dashboard from "./dashboard";

// server component: ดึงจาก FastAPI ตอน render (no-store = สดเสมอ)
export const dynamic = "force-dynamic";

export default async function Home() {
  let analyses: Analysis[] = [];
  let watchlist: WatchlistItem[] = [];
  let changes: ChangeReport[] = [];
  let error: string | null = null;
  try {
    [analyses, watchlist, changes] = await Promise.all([
      getAnalyses(),
      getWatchlist(),
      getChanges(),
    ]);
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }

  return (
    <main className="wrap">
      <header className="top">
        <h1>Investment Research Agent</h1>
        <p>Latest fundamental analysis per watchlist ticker · research, not advice</p>
      </header>

      {error ? (
        <div className="error">
          Cannot reach the API ({error}). Start it with{" "}
          <code>uvicorn src.api.main:app --port 8000</code>
        </div>
      ) : (
        <Dashboard analyses={analyses} watchlist={watchlist} changes={changes} />
      )}

      <p className="disclaimer">
        Educational research tool. Summaries are generated by an LLM from public data and may be
        wrong — always verify against primary sources. Not investment advice.
      </p>
    </main>
  );
}
